services:
  s2app:
    image: prawee/strapi:latest
    container_name: sec2-group-app
    environment:
      DATABASE_CLIENT: ${APP_DB_CLIENT}
      DATABASE_NAME: ${APP_DB_NAME}
      DATABASE_HOST: ${APP_DB_HOST}
      DATABASE_PORT: ${APP_DB_PORT}
      DATABASE_USERNAME: ${APP_DB_USER}
      DATABASE_PASSWORD: ${APP_DB_PASS}
    ports:
      - "${APP_PORT}:${APP_STRAPI_PORT}"
